### ISSUE TITLE
Throws error when i try to run the command

### ISSUE THREAD

**Issue by JemarJones** [TheSavior/ESLint-Formatter#36]
This is on Mac OS Sierra.
```
Error: /Users/jemarjones/Documents/Projects/example/node_modules/.bin/eslint:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sergeybobryk** [comment]
same error

```json
{
 "eslint_path": {
    "windows": "%LOCALAPPDATA%/Yarn/bin/eslint",
    "linux": "/usr/bin/eslint",
    "osx": "/usr/local/bin/eslint"
  }
}
```

**Comment by christophe-g** [comment]
Same error using pnpm

**Comment by johipsum** [comment]
After I [switched to eslint_d](https://github.com/TheSavior/ESLint-Formatter#performance) it worked again for me
